VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "c_Filter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'===============================================================================
' Name:     c_Filter
' Purpose:  篩選邏輯程序的控制器
'===============================================================================
Private Const MODULE_NAME As String = "c_Filter"
' ----- 表單事件 -----

