VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Ent_FieldsTB"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Private Const MODULE_NAME = "Ent_FieldsTB"
'===============================================================================
' Module:   Ent_FieldsTB
' Purpose:
' Layer:    Entity
' Domain:   TB Mapping
'===============================================================================

'--類別成員
Private m_mappings As Dictionary
