VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "m_ServiceValidation"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'===============================================================================
' Name:     m_ServiceValidation
' Purpose:  資料驗證服務，驗計 GL 和 TB 資料是否符合標準
'===============================================================================
Private Const MODULE_NAME = "m_ServiceValidation"
' ----- x -----

