VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "m_ServiceFilter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'===============================================================================
' Name:     m_ServiceFilter
' Purpose:  篩選條件的服務
'===============================================================================

' === 常數 ===
Private Const MODULE_NAME As String = "m_ServiceFilter"

