VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "dal_Sql"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'===============================================================================
' Name:     dal_Sql
' Purpose:  實作 SQL 資料庫的具體操作
'===============================================================================

' === 常數 ===
Private Const MODULE_NAME As String = "dal_Sql"


