VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "m_ServicePowerQuery"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'===============================================================================
' Name:     m_ServicePowerQuery
' Purpose:  定義 Power Query 的服務
'===============================================================================

' === 常數 ===
Private Const MODULE_NAME As String = "m_ServicePowerQuery"


' Should be able to determine M formula and M query.
