VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DbSchemaTarget"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'===============================================================================
' Layer:    Schema
' Name:     Target
' Purpose:  ....
'
'===============================================================================

'--


'-------------------------------------------------------------------------------
'-- Target Layer
'-------------------------------------------------------------------------------



